### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by farridav** [kotrfa/tutos#2]
Github Issues are not really the place for this kind of message, but just wanted to say thanks for putting up your tutorials, I read them all, and found them very useful (As I'm just about to move from ubuntu to arch, and I'm an i3 fan)

Feel free to close this once you've read it, and keep up the good work!

**Comment by kotrfa** [comment]
Hi. Never mind about using github issues for this message. This repo is definitely not strictly ruled :D .

Thank you for the feed back. Don't hesitate with a criticism.  E.g. I know that the English in tutos is horrible. 

Bye, Daniel
